# Generated by Django 3.0.8 on 2020-07-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_birth',
            new_name='birth_date',
        ),
    ]
