# Generated by Django 3.0.8 on 2020-07-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
